name: E2E Tests - Playwright
on:
  pull_request:
    branches: [main, master]
jobs:
  tests:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/view
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm i

      - name: Install global Playwright
        run: npm -g add playwright

      - name: npx playwright install
        run: npx playwright install

      - name: Run Playwright tests
        run: npm test:e2e
